export const data = {
  columns: [
    {
      label: "Name",
      field: "name",
      sort: "asc",
      width: 150,
    },
    {
      label: "age",
      field: "age",
      sort: "asc",
      width: 270,
    },
    {
      label: "gender",
      field: "gender",
      sort: "asc",
      width: 200,
    },
    {
      label: "nationality",
      field: "nationality",
      sort: "asc",
      width: 100,
    },
    {
      label: "family_size",
      field: "family_size",
      sort: "asc",
      width: 150,
    },
    {
      label: "location",
      field: "location",
      sort: "asc",
      width: 100,
    },
    {
      label: "contact",
      field: "contact",
      sort: "asc",
      width: 100,
    },
    {
      label: "status",
      field: "status",
      sort: "asc",
      width: 100,
    },
    {
      label: "education_level",
      field: "education_level",
      sort: "asc",
      width: 100,
    },
    {
      label: "employment_status",
      field: "employment_status",
      sort: "asc",
      width: 100,
    },
  ],
  rows: [
    {
      name: "John Doe",
      age: 28,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 5,
      location: "Juba, South Sudan",
      status: "Displaced",
      contact: "+211-987654321",
      needs: ["food", "shelter", "medical care"],
      priorities: ["safety", "access to clean water", "education"],
      health_conditions: [
        {
          condition: "Malaria",
          treatment: "Antimalarial medication",
          status: "Under treatment",
        },
        {
          condition: "Malnutrition",
          treatment: "Supplementary feeding",
          status: "Recovering",
        },
      ],
      education_level: "Primary school",
      skills: ["farming", "carpentry"],
      languages_spoken: ["English", "Dinka"],
      employment_status: "Unemployed",
    },
    {
      name: "Jane Smith",
      age: 32,
      gender: "Female",
      nationality: "South Sudanese",
      family_size: 3,
      location: "Bor, South Sudan",
      status: "Refugee",
      contact: "+211-987123456",
      needs: ["clean water", "sanitation facilities", "education"],
      priorities: ["safety", "reuniting with family", "access to healthcare"],
      health_conditions: [],
      education_level: "No formal education",
      skills: [],
      languages_spoken: ["English", "Nuer"],
      employment_status: "Unemployed",
    },
    {
      name: "Ali Hassan",
      age: 10,
      gender: "Male",
      nationality: "Somali",
      family_size: 1,
      location: "Yida Refugee Camp, South Sudan",
      status: "Unaccompanied minor",
      contact: "+211-987987654",
      needs: ["shelter", "education", "psychosocial support"],
      priorities: ["reuniting with family", "access to food", "safety"],
      health_conditions: [
        {
          condition: "Post-traumatic stress disorder (PTSD)",
          treatment: "Counseling and therapy",
          status: "Undergoing treatment",
        },
      ],
      education_level: "No formal education",
      skills: [],
      languages_spoken: ["Somali", "Arabic"],
      employment_status: "Unemployed",
    },
    {
      name: "Aisha Ahmed",
      age: 45,
      gender: "Female",
      nationality: "Sudanese",
      family_size: 8,
      location: "Maban, South Sudan",
      status: "Refugee",
      contact: "+211-987789123",
      needs: ["shelter", "food", "healthcare", "education"],
      priorities: ["safety", "access to clean water", "reuniting with family"],
      health_conditions: [
        {
          condition: "Chronic respiratory illness",
          treatment: "Inhalers",
          status: "Managed",
        },
      ],
      education_level: "Secondary school",
      skills: ["sewing", "cooking"],
      languages_spoken: ["Arabic", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Daniel Kwol",
      age: 27,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 2,
      location: "Pariang, South Sudan",
      status: "Displaced",
      contact: "+211-987567890",
      needs: ["shelter", "food", "clean water", "medical care"],
      priorities: ["safety", "access to education", "livelihood opportunities"],
      health_conditions: [],
      education_level: "No formal education",
      skills: ["farming", "animal husbandry"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Maryam Abbas",
      age: 42,
      gender: "Female",
      nationality: "Sudanese",
      family_size: 6,
      location: "Juba, South Sudan",
      status: "Refugee",
      contact: "+211-987654321",
      needs: ["shelter", "food", "clean water", "medical care", "clothing"],
      priorities: [
        "family safety",
        "education for children",
        "employment opportunities",
      ],
      health_conditions: ["diabetes", "hypertension"],
      education_level: "Some primary education",
      skills: ["tailoring", "cooking"],
      languages_spoken: ["Arabic", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Aisha Ibrahim",
      age: 28,
      gender: "Female",
      nationality: "Sudanese",
      family_size: 1,
      location: "Bentiu, South Sudan",
      status: "Unaccompanied minor",
      contact: "+211-987123456",
      needs: [
        "shelter",
        "food",
        "clean water",
        "education",
        "psychosocial support",
      ],
      priorities: [
        "safety",
        "access to education",
        "reunification with family",
      ],
      health_conditions: ["post-traumatic stress disorder"],
      education_level: "Some secondary education",
      skills: ["sewing", "beadwork"],
      languages_spoken: ["Arabic", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "John Deng",
      age: 35,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 3,
      location: "Malakal, South Sudan",
      status: "Displaced",
      contact: "+211-987987987",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
      ],
      priorities: [
        "basic needs",
        "reuniting with family members",
        "access to clean water",
      ],
      health_conditions: [],
      education_level: "No formal education",
      skills: ["carpentry", "construction"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Seasonal laborer",
    },
    {
      name: "Ahmed Mustafa",
      age: 45,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 5,
      location: "Yida, South Sudan",
      status: "Refugee",
      contact: "+211-987987654",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "hygiene items",
      ],
      priorities: [
        "family safety",
        "access to clean water",
        "rebuilding livelihood",
      ],
      health_conditions: ["malaria"],
      education_level: "Some primary education",
      skills: ["fishing", "carpentry"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Casual laborer",
    },
    {
      name: "Grace Lado",
      age: 31,
      gender: "Female",
      nationality: "Sudanese",
      family_size: 2,
      location: "Bor, South Sudan",
      status: "Displaced",
      contact: "+211-987654987",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
      ],
      priorities: ["safety", "access to education", "family reunification"],
      health_conditions: ["malnutrition"],
      education_level: "No formal education",
      skills: ["weaving", "pottery"],
      languages_spoken: ["Arabic", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "James Majok",
      age: 26,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 3,
      location: "Jonglei, South Sudan",
      status: "Displaced",
      contact: "+211-987654321",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "clothing",
      ],
      priorities: ["safety", "access to education", "family reunification"],
      health_conditions: [],
      education_level: "Some secondary education",
      skills: ["carpentry", "bricklaying"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Day laborer",
    },
    {
      name: "Sarah Kuku",
      age: 23,
      gender: "Female",
      nationality: "Sudanese",
      family_size: 1,
      location: "Bentiu, South Sudan",
      status: "Unaccompanied minor",
      contact: "+211-987987123",
      needs: [
        "shelter",
        "food",
        "clean water",
        "education",
        "psychosocial support",
      ],
      priorities: [
        "safety",
        "access to education",
        "reunification with family",
      ],
      health_conditions: [],
      education_level: "Some primary education",
      skills: ["weaving", "beadwork"],
      languages_spoken: ["Arabic", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Joseph Deng",
      age: 36,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 4,
      location: "Malakal, South Sudan",
      status: "Refugee",
      contact: "+211-987123456",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "hygiene items",
      ],
      priorities: [
        "family safety",
        "access to clean water",
        "rebuilding livelihood",
      ],
      health_conditions: [],
      education_level: "Primary education",
      skills: ["farming", "blacksmithing"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Michael Anyang",
      age: 42,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 3,
      location: "Juba, South Sudan",
      status: "Displaced",
      contact: "+211-987654789",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: [],
      education_level: "Some secondary education",
      skills: ["carpentry", "fishing"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Rebecca Akuot",
      age: 28,
      gender: "Female",
      nationality: "South Sudanese",
      family_size: 5,
      location: "Wau, South Sudan",
      status: "Displaced",
      contact: "+211-987654321",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["malaria"],
      education_level: "Some primary education",
      skills: ["farming", "cooking"],
      languages_spoken: ["Dinka", "Arabic"],
      employment_status: "Unemployed",
    },
    {
      name: "Daniel Arop",
      age: 34,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 4,
      location: "Malakal, South Sudan",
      status: "Displaced",
      contact: "+211-987456123",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["chronic back pain"],
      education_level: "Some primary education",
      skills: ["masonry", "carpentry"],
      languages_spoken: ["Nuer", "English"],
      employment_status: "Unemployed",
    },

    {
      name: "Amina Juma",
      age: 25,
      gender: "Female",
      nationality: "South Sudanese",
      family_size: 2,
      location: "Rumbek, South Sudan",
      status: "Displaced",
      contact: "+211-987654789",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["pregnant"],
      education_level: "Some secondary education",
      skills: ["sewing", "beadwork"],
      languages_spoken: ["Dinka", "Arabic"],
      employment_status: "Unemployed",
    },

    {
      name: "Jacob Deng",
      age: 49,
      gender: "Male",
      nationality: "South Sudanese",
      family_size: 7,
      location: "Bor, South Sudan",
      status: "Displaced",
      contact: "+211-987654321",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["diabetes"],
      education_level: "Some primary education",
      skills: ["farming", "animal husbandry"],
      languages_spoken: ["Dinka", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Fatima Ahmed",
      age: 26,
      gender: "Female",
      nationality: "Somalian",
      family_size: 4,
      location: "Mogadishu, Somalia",
      status: "Refugee",
      contact: "+252-123456789",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["malaria"],
      education_level: "No formal education",
      skills: ["cooking", "sewing"],
      languages_spoken: ["Somali", "Arabic"],
      employment_status: "Unemployed",
    },

    {
      name: "Rahul Mehta",
      age: 32,
      gender: "Male",
      nationality: "Indian",
      family_size: 5,
      location: "Rumbek, South Sudan",
      status: "Underprivileged",
      contact: "+91-9876543210",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["asthma"],
      education_level: "High school graduate",
      skills: ["computer programming", "sales"],
      languages_spoken: ["Hindi", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Siti Nurul",
      age: 22,
      gender: "Female",
      nationality: "Indonesian",
      family_size: 6,
      location: "Wau, South Sudan",
      status: "Living in poverty",
      contact: "+62-123456789",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["malnutrition"],
      education_level: "Some high school education",
      skills: ["sewing", "cooking"],
      languages_spoken: ["Indonesian", "English"],
      employment_status: "Unemployed",
    },
    {
      name: "Carlos Hernandez",
      age: 38,
      gender: "Male",
      nationality: "Mexican",
      family_size: 3,
      location: "Jonglei, South Sudan",
      status: "Migrant worker",
      contact: "+52-1234567890",
      needs: [
        "shelter",
        "food",
        "clean water",
        "medical care",
        "education for children",
        "livelihood support",
      ],
      priorities: ["safety", "access to education", "improving livelihood"],
      health_conditions: ["back pain"],
      education_level: "Some high school education",
      skills: ["construction work", "farming"],
      languages_spoken: ["Spanish", "English"],
      employment_status: "Seasonal worker",
    },
  ],
};
